/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Admin: () => import('#controllers/admin_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Checklists: () => import('#controllers/checklists_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Reviews: () => import('#controllers/reviews_controller'),
  Swaps: () => import('#controllers/swaps_controller'),
  UserChecklists: () => import('#controllers/user_checklists_controller'),
}
