"use client";

import { ArrowRight, ArrowUpRight, Layers, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { PublicShell } from "@tcg/ui-web";
import { mockCategories, mockChecklists } from "../../src/lib/mockData";

function ChecklistCard({ checklist }: { checklist: (typeof mockChecklists)[number] }) {
  return <a href={`/collection/${checklist.id}`} className="wax-checklist-card focus-ring"><div className="wax-checklist-card-meta"><span>{checklist.year}</span><span>Card set</span></div><div className="wax-checklist-card-body"><Layers aria-hidden="true" /><h3>{checklist.name}</h3><p>{checklist.category?.name} · {checklist.subcategory?.name}</p></div><div className="wax-checklist-card-foot"><span><strong>{checklist.totalCards}</strong> cards</span><ArrowUpRight aria-hidden="true" /></div></a>;
}

export default function ChecklistsPage() {
  const [search, setSearch] = useState("");
  const results = useMemo(() => { const q = search.trim().toLowerCase(); return (q ? mockChecklists.filter((item) => [item.name, String(item.year), item.category?.name, item.subcategory?.name].some((value) => value?.toLowerCase().includes(q))) : mockChecklists).slice(0, 9); }, [search]);
  return <PublicShell currentPath="/checklists"><section className="wax-public-hero wax-public-hero-catalogue"><div><h1>Find the set.<br />Know the card.</h1><p>Explore catalogues by game, season, and set. Keep card numbers and collection context close before you trade.</p></div><label className="wax-catalogue-search" htmlFor="catalogue-search"><Search aria-hidden="true" /><span className="sr-only">Search catalogues</span><input id="catalogue-search" type="search" placeholder="Search sets, years, or categories" value={search} onChange={(event) => setSearch(event.target.value)} /><span className="wax-search-hint">SET / YEAR</span></label></section><section className="wax-public-section" aria-labelledby="catalogue-results-heading"><div className="wax-public-section-heading"><div><h2 id="catalogue-results-heading">{search ? "Search results" : "Featured collections"}</h2><p>{search ? `${results.length} catalogues match your search.` : "A useful place to start browsing."}</p></div><span className="wax-result-count">{String(results.length).padStart(2, "0")} sets</span></div>{results.length ? <div className="wax-checklist-grid">{results.map((item) => <ChecklistCard key={item.id} checklist={item} />)}</div> : <div className="wax-public-empty"><h3>No catalogue matches “{search}”.</h3><p>Try a set name, release year, or category.</p><button type="button" className="wax-text-link focus-ring" onClick={() => setSearch("")}>Clear search</button></div>}</section><section className="wax-category-index" aria-labelledby="category-index-heading"><div className="wax-category-index-heading"><h2 id="category-index-heading">Browse every category</h2><p>Start broad, then narrow the shelf by series or era.</p></div><div className="wax-category-columns">{mockCategories.map((category, index) => <article key={category.id} className="wax-category-column"><span className="wax-category-number">{String(index + 1).padStart(2, "0")}</span><a href={`/s/${category.id}`} className="wax-category-parent focus-ring"><span>{category.name}</span><ArrowRight aria-hidden="true" /></a>{category.children.length > 0 && <ul>{category.children.map((child) => <li key={child.id}><a href={`/s/${child.id}`} className="focus-ring">{child.name}</a></li>)}</ul>}</article>)}</div></section></PublicShell>;
}
