"use client";

import { useState } from "react";
import { AuthShell } from "@tcg/ui-web";

export default function SignupPage() {
  const [pending, setPending] = useState(false);
  return <AuthShell eyebrow="Join the club / 01" title={<>Make room for <em>more.</em></>} description="Build your collector profile, find your people, and give every card a place in the story." asideTitle="Collection starts with a first pull." asideDescription="Bring your binder online and make every swap, want, and discovery count." asideItems={["A profile made for collecting", "Local context, global community", "WhatsApp-first verification"]} footer={<>Already have a vault? <a href="/login" className="wax-auth-link focus-ring">Sign in</a></>}><form className="wax-auth-form wax-auth-form-signup" onSubmit={(event) => { event.preventDefault(); setPending(true); window.location.assign("/verify-otp"); }}><div className="wax-auth-form-grid">{[["fullName", "Full name", "text", "Your name"], ["username", "Username", "text", "collector_01"], ["email", "Email", "email", "hello@nexus.com"], ["mobile", "Mobile / WhatsApp", "tel", "+20 10 0000 0000"], ["password", "Password", "password", "••••••••"], ["passwordConfirmation", "Confirm password", "password", "••••••••"]].map(([id, label, type, placeholder]) => <div className="wax-auth-field" key={id}><label htmlFor={`signup-${id}`} className="wax-auth-label">{label}</label><div className="wax-auth-input-wrap"><input id={`signup-${id}`} name={id} type={type} placeholder={placeholder} className="wax-auth-input" required disabled={pending} /></div></div>)}<div className="wax-auth-field wax-auth-field-wide"><label htmlFor="signup-governorate" className="wax-auth-label">Region</label><div className="wax-auth-input-wrap"><select id="signup-governorate" name="governorate" className="wax-auth-input" required disabled={pending}><option value="">Select your governorate</option><option>Cairo</option><option>Alexandria</option><option>Giza</option></select></div></div></div><button type="submit" disabled={pending} className="wax-button wax-button-primary wax-auth-submit">{pending ? "Creating profile…" : "Create my profile"}</button></form></AuthShell>;
}
