import type { ReactNode } from "react";
import { ArrowLeft, ArrowRight, Check, MapPin } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";

type AuthShellProps = { eyebrow: string; title: ReactNode; description: string; children: ReactNode; footer: ReactNode; asideTitle: string; asideDescription: string; asideItems: string[] };

export default function AuthShell({ eyebrow, title, description, children, footer, asideTitle, asideDescription, asideItems }: AuthShellProps) {
  const navigate = useNavigate();
  const { i18n } = useTranslation();
  const BackIcon = i18n.language === "ar" ? ArrowRight : ArrowLeft;
  return <main className="auth-shell min-h-dvh bg-background text-foreground"><div className="mx-auto grid min-h-dvh w-full max-w-[1480px] lg:grid-cols-[minmax(360px,0.82fr)_minmax(540px,1.18fr)]">
    <aside className="auth-rail relative hidden overflow-hidden border-r border-border lg:flex lg:flex-col lg:justify-between lg:p-12 xl:p-16"><div className="absolute inset-0 opacity-40" aria-hidden="true"><div className="auth-grid absolute inset-0" /><div className="auth-orbit auth-orbit-one" /><div className="auth-orbit auth-orbit-two" /></div><div className="relative z-10"><Link to="/" className="inline-flex items-center gap-3 font-display text-lg font-bold tracking-tight focus-ring"><img src="/logo_tcg-nexus_primary_20260923.svg" alt="" aria-hidden="true" className="h-9 w-9" /><span>TCG Nexus</span></Link><div className="mt-24 max-w-sm"><p className="font-mono text-xs uppercase tracking-[0.24em] text-primary-500">Collector access / 01</p><h2 className="mt-5 font-display text-5xl font-bold leading-[0.98] tracking-[-0.04em] xl:text-6xl">Your binder,<br /><span className="text-primary-500">in motion.</span></h2><p className="mt-6 max-w-xs text-sm leading-7 text-muted-foreground">{asideDescription}</p></div></div><div className="relative z-10 max-w-sm space-y-5"><div className="border-l-2 border-primary-500 pl-4"><p className="font-display text-lg font-semibold">{asideTitle}</p><p className="mt-1 text-sm text-muted-foreground">Egypt-first collecting, trading, and discovery.</p></div><ul className="space-y-3 text-sm text-muted-foreground">{asideItems.map((item) => <li key={item} className="flex items-center gap-3"><span className="grid h-5 w-5 place-items-center rounded-full bg-primary-500/15 text-primary-500"><Check className="h-3 w-3" /></span>{item}</li>)}</ul><div className="flex items-center gap-2 border-t border-border pt-5 font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground"><MapPin className="h-3.5 w-3.5 text-primary-500" /> Cairo / Alexandria / everywhere</div></div></aside>
    <section className="relative flex min-h-dvh flex-col px-5 py-6 sm:px-8 lg:px-16 lg:py-10 xl:px-24"><div className="flex items-center justify-between"><button type="button" onClick={() => navigate(-1)} aria-label="Go back" className="grid h-11 w-11 place-items-center rounded-xl border border-border bg-card text-muted-foreground transition hover:border-primary-500 hover:text-primary-500 focus-ring"><BackIcon className="h-4 w-4" /></button><Link to="/" className="flex items-center gap-2 font-display font-bold lg:hidden focus-ring"><img src="/logo_tcg-nexus_primary_20260923.svg" alt="" aria-hidden="true" className="h-8 w-8" />TCG Nexus</Link><span className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">TCG / 2026</span></div><div className="mx-auto flex w-full max-w-[500px] flex-1 flex-col justify-center py-12"><header className="mb-8"><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary-500">{eyebrow}</p><h1 className="mt-4 font-display text-4xl font-bold leading-tight tracking-[-0.04em] sm:text-5xl">{title}</h1><p className="mt-4 max-w-md text-[15px] leading-7 text-muted-foreground">{description}</p></header>{children}<div className="mt-8 border-t border-border pt-6 text-center text-sm text-muted-foreground">{footer}</div></div><p className="text-center font-mono text-[10px] uppercase tracking-[0.16em] text-muted-foreground/70">Private collection space · Secure session</p></section>
  </div></main>;
}
