/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CategoryTransformer from '#transformers/category_transformer'
import type ChecklistTransformer from '#transformers/checklist_transformer'
import type UserChecklistTransformer from '#transformers/user_checklist_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Category = InferData<CategoryTransformer>
  export namespace Category {
    export type Variants = InferVariants<CategoryTransformer>
  }
  export type Checklist = InferData<ChecklistTransformer>
  export namespace Checklist {
    export type Variants = InferVariants<ChecklistTransformer>
  }
  export type UserChecklist = InferData<UserChecklistTransformer>
  export namespace UserChecklist {
    export type Variants = InferVariants<UserChecklistTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
