/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CardSchema extends BaseModel {
  static $columns = ['checklistId', 'createdAt', 'holdCount', 'id', 'name', 'needCount', 'number', 'offerCount', 'order', 'ratio', 'section', 'status', 'type', 'updatedAt', 'version'] as const
  $columns = CardSchema.$columns
  @column()
  declare checklistId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare holdCount: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare needCount: number | null
  @column()
  declare number: string
  @column()
  declare offerCount: number | null
  @column()
  declare order: number
  @column()
  declare ratio: string | null
  @column()
  declare section: string | null
  @column()
  declare status: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class CatalogueImportSchema extends BaseModel {
  static $columns = ['actorId', 'checksum', 'createdAt', 'id', 'status', 'summary', 'updatedAt'] as const
  $columns = CatalogueImportSchema.$columns
  @column()
  declare actorId: number | null
  @column()
  declare checksum: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column()
  declare summary: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'parentId', 'slug', 'status', 'updatedAt', 'version'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare parentId: number
  @column()
  declare slug: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class ChecklistSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'id', 'name', 'status', 'subcategoryId', 'totalCards', 'type', 'updatedAt', 'version', 'year'] as const
  $columns = ChecklistSchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare status: string
  @column()
  declare subcategoryId: number | null
  @column()
  declare totalCards: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
  @column()
  declare year: number
}

export class ConversationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt', 'user1Id', 'user2Id'] as const
  $columns = ConversationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare user1Id: number | null
  @column()
  declare user2Id: number | null
}

export class IdentityIdempotencyKeySchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'fingerprint', 'id', 'key', 'responseJson', 'scope', 'status'] as const
  $columns = IdentityIdempotencyKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare fingerprint: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare responseJson: string
  @column()
  declare scope: string
  @column()
  declare status: number
}

export class MessageSchema extends BaseModel {
  static $columns = ['content', 'conversationId', 'createdAt', 'dealId', 'id', 'isRead', 'senderId', 'type', 'updatedAt'] as const
  $columns = MessageSchema.$columns
  @column()
  declare content: string
  @column()
  declare conversationId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dealId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRead: boolean | null
  @column()
  declare senderId: number | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OtpChallengeSchema extends BaseModel {
  static $columns = ['attempts', 'codeHash', 'consumedAt', 'createdAt', 'expiresAt', 'id', 'maxAttempts', 'mobile', 'purpose', 'updatedAt', 'userId'] as const
  $columns = OtpChallengeSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare codeHash: string
  @column.dateTime()
  declare consumedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxAttempts: number
  @column()
  declare mobile: string
  @column()
  declare purpose: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class PrivacyExportSchema extends BaseModel {
  static $columns = ['createdAt', 'downloadToken', 'expiresAt', 'id', 'status', 'updatedAt', 'userId'] as const
  $columns = PrivacyExportSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare downloadToken: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class ReviewSchema extends BaseModel {
  static $columns = ['comment', 'createdAt', 'id', 'reviewerId', 'targetUserId', 'type', 'updatedAt'] as const
  $columns = ReviewSchema.$columns
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reviewerId: number | null
  @column()
  declare targetUserId: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SwapDealSchema extends BaseModel {
  static $columns = ['conversationId', 'createdAt', 'createdByUserId', 'id', 'offeredCards', 'requestedCards', 'status', 'swapType', 'updatedAt', 'user1PhotoUrl', 'user1QrScanned', 'user1Received', 'user1Tracking', 'user2PhotoUrl', 'user2QrScanned', 'user2Received', 'user2Tracking'] as const
  $columns = SwapDealSchema.$columns
  @column()
  declare conversationId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare offeredCards: string
  @column()
  declare requestedCards: string
  @column()
  declare status: string | null
  @column()
  declare swapType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare user1PhotoUrl: string | null
  @column()
  declare user1QrScanned: boolean | null
  @column()
  declare user1Received: boolean | null
  @column()
  declare user1Tracking: string | null
  @column()
  declare user2PhotoUrl: string | null
  @column()
  declare user2QrScanned: boolean | null
  @column()
  declare user2Received: boolean | null
  @column()
  declare user2Tracking: string | null
}

export class UserChecklistSchema extends BaseModel {
  static $columns = ['checklistId', 'collectedList', 'createdAt', 'duplicatesList', 'id', 'missingList', 'updatedAt', 'userId'] as const
  $columns = UserChecklistSchema.$columns
  @column()
  declare checklistId: number | null
  @column()
  declare collectedList: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare duplicatesList: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare missingList: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['anonymizedAt', 'blocked', 'communicationPreferences', 'createdAt', 'deactivatedAt', 'email', 'fullName', 'governorate', 'id', 'isVerified', 'lastLoginAt', 'locale', 'mobile', 'notReadyForSwap', 'otpCode', 'password', 'privacyPreferences', 'role', 'status', 'theme', 'updatedAt', 'username', 'version'] as const
  $columns = UserSchema.$columns
  @column.dateTime()
  declare anonymizedAt: DateTime | null
  @column()
  declare blocked: boolean
  @column()
  declare communicationPreferences: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deactivatedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare fullName: string | null
  @column()
  declare governorate: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isVerified: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare locale: string
  @column()
  declare mobile: string
  @column()
  declare notReadyForSwap: boolean
  @column()
  declare otpCode: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare privacyPreferences: string | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column()
  declare theme: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
  @column()
  declare version: number
}
