export const EGYPT_GOVERNORATES = [
  'Cairo',
  'Alexandria',
  'Giza',
  'Dakahlia',
  'Red Sea',
  'Beheira',
  'Fayoum',
  'Gharbia',
  'Ismailia',
  'Monufia',
  'Minya',
  'Qalyubia',
  'New Valley',
  'Sharqia',
  'Suez',
  'Aswan',
  'Assiut',
  'Beni Suef',
  'Port Said',
  'Damietta',
  'South Sinai',
  'Kafr El Sheikh',
  'Matrouh',
  'Luxor',
  'Qena',
  'Sohag',
  'North Sinai',
] as const;

export type Governorate = (typeof EGYPT_GOVERNORATES)[number];
