import { ArrowLeft, ArrowRight, MapPin, ShieldCheck } from "lucide-react";
import { EmptyStatePanel, PublicShell, buttonStyles, textLinkStyles } from "@tcg/ui-web";
import { mockMarketplaceListings } from "../../../../src/lib/mockData";

export default async function ListingPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const listing = mockMarketplaceListings.find((item) => item.id === id);
  if (!listing) return <PublicShell currentPath="/marketplace"><section className="wax-public-empty-page"><EmptyStatePanel title="Listing not found." description="This card may no longer be on the trade floor." action={<a href="/marketplace" className={buttonStyles()}><ArrowLeft aria-hidden="true" /> Back to marketplace</a>} /></section></PublicShell>;
  return <PublicShell currentPath="/marketplace"><article className="wax-market-detail"><div className="wax-market-detail-nav"><a href="/marketplace" className={textLinkStyles()}><ArrowLeft aria-hidden="true" /> All listings</a><span>Demo marketplace listing</span></div><div className="wax-market-detail-grid"><div className="wax-market-detail-image"><img src={listing.image} alt={`${listing.title} card`} /><span>{listing.condition}</span></div><div className="wax-market-detail-copy"><p className="wax-market-set">{listing.set}</p><h1>{listing.title}</h1><p className="wax-market-price">EGP {listing.price.toLocaleString("en-EG")}</p><p className="wax-market-description">Review the set, condition, and seller before starting a conversation. This preview does not process payment or delivery; confirm exchange details directly with the seller.</p><dl className="wax-market-facts"><div><dt>Condition</dt><dd>{listing.condition}</dd></div><div><dt>Seller</dt><dd>{listing.seller}</dd></div><div><dt>Location</dt><dd><MapPin aria-hidden="true" /> Egypt</dd></div></dl><div className="wax-market-actions"><a href="/login" className={buttonStyles()}>Sign in to contact seller <ArrowRight aria-hidden="true" /></a><a href="/checklists" className={textLinkStyles()}>Check the catalogue</a></div><p className="wax-demo-note"><ShieldCheck aria-hidden="true" /> Demonstration listing. Confirm card and seller details before any exchange.</p></div></div></article></PublicShell>;
}
